[Loads]
Publish = [ "Powers",]
NoPublish = [ "VoltagesMagAng",]

[PVSystems]
Publish = [ "Powers", "VoltagesMagAng",]
NoPublish = []

[Storages]
Publish = []
NoPublish = [ "Powers", "VoltagesMagAng", "%stored",]

[Buses]
Publish = []
NoPublish = [ "puVmagAngle", "Distance", "kVBase", "Name", "Nodes"]

[Circuits]
Publish = [ "TotalPower", "LineLosses", "Losses", "SubstationLosses",]
NoPublish = []

[Lines]
Publish = []
NoPublish = [ "CurrentsMagAng", "normamps", "bus1", "bus2", "enabled", "nodeorder"]

[Transformers]
Publish = []
NoPublish = [ "CurrentsMagAng", "normamps", "taps", "bus1", "bus2", "enabled","nodeorder"]

[Faults]
Publish = []
NoPublish = [ "bus1", "bus2", "enabled"]