
"Project Path" = "C:\\Users\\alatif\\Desktop\\PyDSS\\examples\\External_interfacing_example"
"Simulation Type" = "QSTS"
"Active Project" = "pyDSS_project"
"Active Scenario" = "api_interface"
"DSS File" = "Master_Spohn_existing_VV.dss"
"Return Results" = true
"Logging Level" = "DEBUG"