
"Project Path" = "C:\\Users\\alatif\\Desktop\\PyDSS\\examples"
"Simulation Type" = "QSTS"
"Active Project" = "Harmonics_examples"
"Active Scenario" = "freq_scan_qsts"
"DSS File" = "Run_Scan.dss"
"Enable frequency sweep" = true
"Fundamental frequency" = 60
"Start frequency" = 1.0
"End frequency" = 15.0
"frequency increment" = 0.0833333333333333
"Neglect shunt admittance" = false
"Percentage load in series" = 50.0
"Create dynamic plots" = true
"Open plots in browser" = true


