[Simulations]
	
Run_simulations = false
Generate_visuals = true
Run_bokeh_server = false

[Plots]

Frequency_sweep = false
XFMR_tap = true
Voltage_sag = true
Voltage = true
Loading = true
Voltage_Loading = true
Voltage_profiles = true
Load = true
Generation = true
Load_Generation = true
Curtailment = true
Voltage_imbalance = true
Feeder_power = true
Feeder_line_losses = true
Feeder_losses = true
Feeder_substation_losses = true
