"Project Path" = "C:\\Users\\alatif\\Desktop\\PyDSS\\examples"
"Simulation Type" = "QSTS"
"Active Project" = "Monte_carlo_examples"
"Active Scenario" = "monte_carlo"
"DSS File" = "Master_Spohn_existing_VV.dss"
"Number of Monte Carlo scenarios" = 5
