[settings]
"uuid" = "nrel_1"
"training period (hours)" = 24.0
"retraining period (hours)" = 24.0

[assets]
[[assets.Capacitors]]
"measure" = "from list" #"all", "from list", "use regex"
"values" = ["CAP_STATE", "PRIMARY_V", "PRIMARY_P", "PRIMARY_Q"]
"list" = ["cap1"]
"Controllable" = true
"regex" = ""
[[assets.Capacitors]]
"measure" = "from list" #"all", "from list", "use regex"
"values" = ["CAP_STATE"]
"list" = ["cap2"]
"regex" = ""
"Controllable" = false
[[assets.Loads]]
"measure" = "all" #"all", "from list", "use regex"
"values" = ["AMI_V_120", "AMI_P"]
"list" = []
"regex" = ""
"Controllable" = false
[[assets.Transformers]]
"measure" = "use regex" #"all", "from list", "use regex"
"values" = ["TAP_POSITION", "PRIMARY_V", "PRIMARY_P", "PRIMARY_Q"]
"list" = []
"regex" = ".reg"
"Controllable" = true
[[assets.Lines]]
"measure" = "all" #"all", "from list", "use regex"
"values" = ["SWITCH_STATE", "PRIMARY_V"]
"list" = []
"regex" = ""
"Controllable" = true
[[assets.Vsources]]
"measure" = "all" #"all", "from list", "use regex"
"values" = ["SWING_V", "SWING_P", "SWING_Q"]
"list" = []
"regex" = ""
"Controllable" = false

